# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFIgQeflGYxg3gTRhe1pT_DITiUlR3oB

# Data Science Tools and Ecosystem

##Autor:
Diego Montero San Martín

En este cuaderno, se resumen las herramientas y ecosistemas de ciencia de datos.

Objetivos:
- Conocer algunos de los lenguajes más populares para ciencia de datos
- Conocer algunas de las bibliotecas más usadas en Python para ciencia de datos
- Conocer algunas herramientas empleadas en ciencia de datos
- Realizar algunos pequeños códigos de prueba

Algunos de los lenguajes populares que utilizan los científicos de datos son:
1. Python
2. R
3. Scala

Algunas de las bibliotecas comúnmente utilizadas por los científicos de datos incluyen:
1. Pandas
2. Seaborn
3. Numpy

|Herramientas de Ciencia de datos|
|--------------------------------|
|MySQL                           |
|Apache Spark                    |
|Jupyter Notebooks               |

### A continuación, se presentan algunos ejemplos de evaluación de expresiones aritméticas en Python:
"""

(3*4)+5

min = 200
hr= min/60
print (hr)